[mongo]
uri = "mongodb+srv://vijaytadala2105:Go5FQXBdnLTU3L5F@cluster0.h4el0fb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
dbname = "vijayam"

[auth]
admin_password = "$2b$12$WpbnRiZamO6s12CyQ50suuj8NNUBO3Z2tfO1tammn6UhZ2.C4JUBe"
user_password = "$2b$12$DR5.UQIvViypNipZUgEuv.pEu/KsV7gU7ZZd2B7wkLx3ornVBFSsC"